{"identifier":{"url":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/UnboundLocalError(_:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/SwiftPy\/documentation\/SwiftPy","doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnboundLocalError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"platforms":["macOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftpy\/pythonerror\/unboundlocalerror(_:)"]}],"metadata":{"title":"PythonError.UnboundLocalError(_:)","role":"symbol","symbolKind":"case","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnboundLocalError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"modules":[{"name":"SwiftPy"}],"externalID":"s:7SwiftPy11PythonErrorO012UnboundLocalD0yACSScACmF"},"kind":"symbol","references":{"doc://SwiftPy/documentation/SwiftPy/PythonError":{"abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"text":"PythonError","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PythonError","kind":"identifier"}],"title":"PythonError","url":"\/documentation\/swiftpy\/pythonerror","identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError"},"doc://SwiftPy/documentation/SwiftPy":{"identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy","title":"SwiftPy","role":"collection","url":"\/documentation\/swiftpy","abstract":[],"kind":"symbol","type":"topic"},"doc://SwiftPy/documentation/SwiftPy/PythonError/UnboundLocalError(_:)":{"url":"\/documentation\/swiftpy\/pythonerror\/unboundlocalerror(_:)","identifier":"doc:\/\/SwiftPy\/documentation\/SwiftPy\/PythonError\/UnboundLocalError(_:)","title":"PythonError.UnboundLocalError(_:)","type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnboundLocalError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]}}}